import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}

function Navbar() {
  return(
    <div className='navbar'>
      <div className='nav-item'><Link href='/'><p>Home</p></Link></div>
      <div className='nav-item'><Link href='/list'><p>List</p></Link></div>
      <div className='nav-item'><Link href='/new'><p>New</p></Link></div>
    </div>
  )
}